
# Practice Day 9

##### Datetime mastery — parsing messy dates
##### Date parsing, dt accessor, duration, messy string cleaning

##### Q1 Load datetime_demo.xlsx. Parse the launched and deadline columns as proper datetimes. Extract year, month, day, and hour from launched into separate columns.
##### Q2 Calculate campaign_duration in days (deadline minus launched). What is the average, min, and max campaign duration?
##### Q3 The messy_date column contains values like "&10\\201509". Clean it to extract a proper date. (Hint: strip the "&", split on "\\", and reconstruct month + year.)
##### Q4 Group campaigns by launch month (1–12). Which month sees the most campaign launches? Which month has the highest average goal?
##### Q5 Find campaigns that launched and had a deadline in the same calendar month. How many are there, and what is their average goal vs campaigns that span across months?

In [39]:
import pandas as pd
import numpy as np
df=pd.read_excel(r"C:\Users\user\Desktop\Python1\DataSample\datetime_demo.xlsx")
print(df.head())

           ID     goal             launched    deadline   messy_date
0  1000002330   1000.0  2015-08-11 12:12:28  2015-10-09  &10\\201509
1  1000003930  30000.0  2017-09-02 04:43:57  2017-11-01  &11\\201701
2  1000004038  45000.0  2013-01-12 00:20:50  2013-02-26  &02\\201326
3  1000007540   5000.0  2012-03-17 03:24:11  2012-04-16  &04\\201216
4  1000011046  19500.0  2015-07-04 08:35:03  2015-08-29  &08\\201529

In [40]:
# Q1 Load datetime_demo.xlsx. 
# Parse the launched and deadline columns as proper datetimes. 
# Extract year, month, day, and hour from launched into separate columns.

In [41]:
df['launched'] = pd.to_datetime(df['launched'])
df['deadline'] = pd.to_datetime(df['deadline'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          4020 non-null   int64
 1   goal        4020 non-null   float64
 2   launched    4020 non-null   datetime64[ns]
 3   deadline    4020 non-null   datetime64[ns]
 4   messy_date  4020 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(1), object(1)
memory usage: 157.2+ KB

In [42]:
df['launched year'] = df['launched'].dt.year
df['launched month'] = df['launched'].dt.month
df['launched day'] = df['launched'].dt.day
df['launched hour'] = df['launched'].dt.hour
df.head()

,ID,goal,launched,deadline,messy_date,launched year,launched month,launched day,launched hour
0,1000002330,1000.0,2015-08-11 12:12:28,2015-10-09,&10\\201509,2015,8,11,12
1,1000003930,30000.0,2017-09-02 04:43:57,2017-11-01,&11\\201701,2017,9,2,4
2,1000004038,45000.0,2013-01-12 00:20:50,2013-02-26,&02\\201326,2013,1,12,0
3,1000007540,5000.0,2012-03-17 03:24:11,2012-04-16,&04\\201216,2012,3,17,3
4,1000011046,19500.0,2015-07-04 08:35:03,2015-08-29,&08\\201529,2015,7,4,8

In [43]:
# Q2 Calculate campaign_duration in days (deadline minus launched). 
# What is the average, min, and max campaign duration?

In [118]:
df['campaign_duration'] = (df['deadline'] - df['launched']).dt.days
df.head()

,ID,goal,launched,deadline,messy_date,launched year,launched month,launched day,launched hour,campaign_duration,new_messy_date
0,1000002330,1000.0,2015-08-11 12:12:28,2015-10-09,2015-10-09,2015,8,11,12,58,10-2015
1,1000003930,30000.0,2017-09-02 04:43:57,2017-11-01,2017-11-01,2017,9,2,4,59,11-2017
2,1000004038,45000.0,2013-01-12 00:20:50,2013-02-26,2013-02-26,2013,1,12,0,44,02-2013
3,1000007540,5000.0,2012-03-17 03:24:11,2012-04-16,2012-04-16,2012,3,17,3,29,04-2012
4,1000011046,19500.0,2015-07-04 08:35:03,2015-08-29,2015-08-29,2015,7,4,8,55,08-2015

In [119]:
df['campaign_duration'].agg(['mean','min','max'])

mean       36.753483
min         0.000000
max     14866.000000
Name: campaign_duration, dtype: float64

In [46]:
# Q3 The messy_date column contains values like "&10\\201509". 
# Clean it to extract a proper date. (Hint: strip the "&", split on "\\", and reconstruct month + year.)

In [47]:
df['messy_date'] = pd.to_datetime(df['messy_date'], format = r'&%m\\%Y%d')

In [16]:
df.head()

,ID,goal,launched,deadline,messy_date,launched year,launched month,launched day,launched hour,campaign_duration
0,1000002330,1000.0,2015-08-11 12:12:28,2015-10-09,2015-10-09,2015,8,11,12,-2
1,1000003930,30000.0,2017-09-02 04:43:57,2017-11-01,2017-11-01,2017,9,2,4,-1
2,1000004038,45000.0,2013-01-12 00:20:50,2013-02-26,2013-02-26,2013,1,12,0,14
3,1000007540,5000.0,2012-03-17 03:24:11,2012-04-16,2012-04-16,2012,3,17,3,-1
4,1000011046,19500.0,2015-07-04 08:35:03,2015-08-29,2015-08-29,2015,7,4,8,25

In [56]:
df['new_messy_date'] = df['messy_date'].dt.strftime('%m-%Y')
df.head()

,ID,goal,launched,deadline,messy_date,launched year,launched month,launched day,launched hour,campaign_duration,new_messy_date
0,1000002330,1000.0,2015-08-11 12:12:28,2015-10-09,2015-10-09,2015,8,11,12,-2,10-2015
1,1000003930,30000.0,2017-09-02 04:43:57,2017-11-01,2017-11-01,2017,9,2,4,-1,11-2017
2,1000004038,45000.0,2013-01-12 00:20:50,2013-02-26,2013-02-26,2013,1,12,0,14,02-2013
3,1000007540,5000.0,2012-03-17 03:24:11,2012-04-16,2012-04-16,2012,3,17,3,-1,04-2012
4,1000011046,19500.0,2015-07-04 08:35:03,2015-08-29,2015-08-29,2015,7,4,8,25,08-2015

In [ ]:
# Q4 Group campaigns by launch month (1–12).

In [80]:
df_q4 = df.groupby('launched month').agg({'ID':'size', 'goal':'mean'}).reset_index()
print(df_q4.sort_values('ID', ascending = False))
print(df_q4.sort_values('goal', ascending = False))

    launched month   ID           goal
6                7  385   31913.451948
7                8  374  140814.951872
4                5  371   18666.247925
10              11  367   25070.171662
5                6  355   29089.476056
9               10  346   31474.881503
1                2  339   71267.533923
2                3  338   31520.878698
8                9  337   26740.943620
3                4  315   29877.377778
0                1  274   25179.507299
11              12  219   16591.575342
    launched month   ID           goal
7                8  374  140814.951872
1                2  339   71267.533923
6                7  385   31913.451948
2                3  338   31520.878698
9               10  346   31474.881503
3                4  315   29877.377778
5                6  355   29089.476056
8                9  337   26740.943620
0                1  274   25179.507299
10              11  367   25070.171662
4                5  371   18666.247925
11              12  219   16591.575342

In [81]:
# Which month sees the most campaign launches? 
print('Month with the most campaign launches:',*df_q4[df_q4['ID'] == df_q4['ID'].max()]['launched month'])

Month with the most campaign launches: 7

In [82]:
# Which month has the highest average goal?
print('Month with the highest average goal:',*df_q4[df_q4['goal'] == df_q4['goal'].max()]['launched month'])

Month with the highest average goal: 8

In [ ]:
# Q5 Find campaigns that launched and had a deadline in the same calendar month. 
# How many are there, and what is their average goal vs campaigns that span across months?

In [ ]:
# How many are there?
print('# of campaigns that launched and had a deadline in the same calendar month:',df[df['deadline'].dt.month == df['launched month']]['ID'].count())

# of campaigns that launched and had a deadline in the same calendar month: 308

In [100]:
# What is their average goal?
avg_goal_samemonth = df[df['deadline'].dt.month == df['launched month']]['goal'].mean().round(2)

In [101]:
# what is average goal campaigns that span across months?
avg_goal_xmonth =df[df['deadline'].dt.month != df['launched month']]['goal'].mean().round(2)

In [116]:
# What is their average goal vs campaigns that span across months?
print('Difference b/w their average goal vs campaigns that span across months:', (100-(avg_goal_samemonth / avg_goal_xmonth*100)).round(2), 'smaller')

Difference b/w their average goal vs campaigns that span across months: 77.05 smaller