# Practice Day 4

##### Salaries — GROUP BY & aggregation
##### groupby, agg, HAVING equivalent, transform
##### Q1 How many unique job titles are there? What are the top 10 most common job titles?
##### Q2 Calculate average, min, max, and total TotalPay per Year. Which year had the highest average pay?
##### Q3 Find job titles with more than 100 employees AND average TotalPay above $100,000. (HAVING equivalent)
##### Q4 Add a dept_avg_pay column showing the average TotalPay for each JobTitle using transform(). Then find employees earning more than 50% above their job title average.
##### Q5 Handle nulls in BasePay and Benefits. Fill BasePay nulls with the median, drop rows where TotalPay is null. Report how many rows were affected.

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\salaries.csv")
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [ ]:
# Q1 How many unique job titles are there? What are the top 10 most common job titles?

In [5]:
df['JobTitle'].value_counts().reset_index().head(10)

                       JobTitle  count
0              Transit Operator   7036
1                 Special Nurse   4389
2              Registered Nurse   3736
3  Public Svc Aide-Public Works   2518
4              Police Officer 3   2421
5                     Custodian   2418
6              TRANSIT OPERATOR   2388
7                   Firefighter   2359
8             Recreation Leader   1971
9        Patient Care Assistant   1945

In [ ]:
# Q2 Calculate average, min, max, and total TotalPay per Year. Which year had the highest average pay?

In [9]:
df.groupby('Year').agg(
    average = ('TotalPay', 'mean'),
    min = ('TotalPay', 'min'),
    max = ('TotalPay', 'max'),
    total = ('TotalPay', 'sum')
).reset_index().nlargest(1,'average')

   Year       average  min        max         total
2  2013  77611.443142  0.0  347102.32  2.918656e+09

In [14]:
# Q3 Find job titles with more than 100 employees AND average TotalPay above $100,000. (HAVING equivalent)
df_q3 = df.groupby('JobTitle').agg(
    emp_cnt = ('Id', 'count'),
    avg_totalpay = ('TotalPay', 'mean')
).reset_index()
df_q3[(df_q3['emp_cnt']>100) & (df_q3['avg_totalpay']>100000)][['JobTitle']]

                           JobTitle
101       ATTORNEY (CIVIL/CRIMINAL)
200                  Assoc Engineer
221       Attorney (Civil/Criminal)
288              Building Inspector
426                       Captain 3
...                             ...
1941  Sr. Stationary Eng, Sew Plant
2016             TRANSIT SUPERVISOR
2064             Transit Supervisor
2087                Utility Plumber
2091             Utility Specialist

[67 rows x 1 columns]

In [ ]:
# Q4 Add a dept_avg_pay column showing the average TotalPay for each JobTitle using transform(). Then find employees earning more than 50% above their job title average.

In [19]:
df['dept_avg_pay'] = df.groupby('JobTitle')['TotalPay'].transform('mean')
df.head()
df[df['TotalPay'] > df['dept_avg_pay']*1.5][['EmployeeName']]

                   EmployeeName
1                  GARY JIMENEZ
2                ALBERT PARDINI
3             CHRISTOPHER CHONG
17               SEBASTIAN WONG
22                GEORGE GARCIA
...                         ...
147979  William Scott Ellsworth
148163         Ronald J Vernali
148233           Amy S Ackerman
148269              Mary Y Jung
148292            Ruth Gravanis

[10575 rows x 1 columns]

In [ ]:
# Q5 Handle nulls in BasePay and Benefits. Fill BasePay nulls with the median, drop rows where TotalPay is null. Report how many rows were affected.

In [31]:
BasePay_null = df['BasePay'].isna().sum()
print(f"\nBasePay null count: {BasePay_null}")
df['BasePay'] = df['BasePay'].fillna(df['BasePay'].median())

BasePay null count: 609

In [26]:
df.dropna(subset=['TotalPay'])

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,dept_avg_pay
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN,399211.275000
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN,211783.893243
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN,211783.893243
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN,145073.492500
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN,279359.560000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN,47070.542419
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN,0.000000
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN,0.000000
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN,0.000000
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN,60715.604603