# Practice Day 3

##### Country demographics — sorting & ranking
##### Sorting, ranking, nlargest, combining conditions
##### Q1 Sort countries by Birth rate descending. Show the top 10 highest birth rate countries.
##### Q2 Sort by Internet users descending. Which 5 countries have the highest internet usage?
##### Q3 Add a birth_rate_rank column ranking all countries from highest to lowest birth rate.
##### Q4 Find all High income countries with internet usage above 80%. How many are there?
##### Q5 Sort by Income Group ASC, then Internet users DESC within each group. Show the top internet user per income group.

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\user\Desktop\Python1\DataSample\demographic_data.csv")
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    195 non-null    object
 1   Country Code    195 non-null    object
 2   Birth rate      195 non-null    float64
 3   Internet users  195 non-null    float64
 4   Income Group    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

,Country Name,Country Code,Birth rate,Internet users,Income Group
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [ ]:
# Q1 Sort countries by Birth rate descending. Show the top 10 highest birth rate countries.

In [34]:
df.sort_values(by = 'Birth rate', ascending=0).head(10)
df.nlargest(10,'Birth rate')

,Country Name,Country Code,Birth rate,Internet users,Income Group,birth_rate_rank
127,Niger,NER,49.661,1.7,Low income,1.0
2,Angola,AGO,45.985,19.1,Upper middle income,2.0
167,Chad,TCD,45.745,2.3,Low income,3.0
11,Burundi,BDI,44.151,1.3,Low income,4.0
115,Mali,MLI,44.138,3.5,Low income,5.0
156,Somalia,SOM,43.891,1.5,Low income,6.0
178,Uganda,UGA,43.474,16.2,Low income,7.0
65,"Gambia, The",GMB,42.525,14.0,Low income,8.0
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,9.0
14,Burkina Faso,BFA,40.551,9.1,Low income,10.0

In [ ]:
# Q2 Sort by Internet users descending. Which 5 countries have the highest internet usage?

In [7]:
df.sort_values(by='Internet users',ascending = True).tail()

    Country Name Country Code  Birth rate  Internet users Income Group
47       Denmark          DNK        10.0         94.6297  High income
163       Sweden          SWE        11.8         94.7836  High income
131       Norway          NOR        11.6         95.0534  High income
22       Bermuda          BMU        10.4         95.3000  High income
84       Iceland          ISL        13.4         96.5468  High income

In [38]:
df.nlargest(5,'Internet users')[::-1]

,Country Name,Country Code,Birth rate,Internet users,Income Group,birth_rate_rank
47,Denmark,DNK,10.0,94.6297,High income,176.0
163,Sweden,SWE,11.8,94.7836,High income,149.0
131,Norway,NOR,11.6,95.0534,High income,151.0
22,Bermuda,BMU,10.4,95.3000,High income,165.0
84,Iceland,ISL,13.4,96.5468,High income,132.0

In [13]:
# Q3 Add a birth_rate_rank column ranking all countries from highest to lowest birth rate.
df['birth_rate_rank'] = df['Birth rate'].rank(method='min',ascending = False)
df.sort_values(by = 'Birth rate', ascending=0).tail(10)

,Country Name,Country Code,Birth rate,Internet users,Income Group,birth_rate_rank
53,Spain,ESP,9.100,71.6350,High income,186.0
19,Bosnia and Herzegovina,BIH,9.062,57.7900,Upper middle income,187.0
146,Romania,ROU,8.800,49.7645,Upper middle income,188.0
95,"Korea, Rep.",KOR,8.600,84.7700,High income,189.0
68,Greece,GRC,8.500,59.8663,High income,190.0
45,Germany,DEU,8.500,84.1700,High income,190.0
86,Italy,ITA,8.500,58.4593,High income,190.0
89,Japan,JPN,8.200,89.7100,High income,193.0
142,Portugal,PRT,7.900,62.0956,High income,194.0
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income,194.0

In [ ]:
# Q4 Find all High income countries with internet usage above 80%. How many are there?

In [18]:
df[(df['Internet users']>80) & (df['Income Group'] == 'High income')].shape[0]

25

In [24]:
#Q5 Sort by Income Group ASC, then Internet users DESC within each group. Show the top internet user per income group.
df.sort_values(by='Income Group').groupby('Income Group')['Internet users'].nlargest(1)

Income Group
High income          84     96.5468
Low income           194    18.5000
Lower middle income  109    56.0000
Upper middle income  98     70.5000
Name: Internet users, dtype: float64

In [30]:
df.sort_values(by='Income Group').groupby('Income Group').apply(lambda x: x.nlargest(1, 'Internet users'))

C:\Users\user\AppData\Local\Temp\ipykernel_21204\1947187854.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.sort_values(by='Income Group').groupby('Income Group').apply(lambda x: x.nlargest(1, 'Internet users'))

,,Country Name,Country Code,Birth rate,Internet users,Income Group,birth_rate_rank
Income Group,,,,,,,
High income,84,Iceland,ISL,13.400,96.5468,High income,132.0
Low income,194,Zimbabwe,ZWE,35.715,18.5000,Low income,27.0
Lower middle income,109,Morocco,MAR,21.023,56.0000,Lower middle income,84.0
Upper middle income,98,Lebanon,LBN,13.426,70.5000,Upper middle income,131.0

In [31]:
df.sort_values(by='Income Group').groupby('Income Group').apply(lambda x: x.nlargest(1, 'Internet users'), include_groups = False)

,,Country Name,Country Code,Birth rate,Internet users,birth_rate_rank
Income Group,,,,,,
High income,84,Iceland,ISL,13.400,96.5468,132.0
Low income,194,Zimbabwe,ZWE,35.715,18.5000,27.0
Lower middle income,109,Morocco,MAR,21.023,56.0000,84.0
Upper middle income,98,Lebanon,LBN,13.426,70.5000,131.0